---
name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish-platformio:
    name: Publish to PlatformIO
    runs-on: ubuntu-latest
    environment: platformio
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.x"

      - name: Install PlatformIO
        run: pip install --upgrade platformio

      - name: Publish package
        env:
          PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
        run: pio package publish --owner esphome --non-interactive
